model_g_url = https://drive.google.com/uc?export=download&id=1f_ELVcFQbvcIU-a4CbChiia7OhwmlASS
model_c_url = https://drive.google.com/uc?export=download&id=1XqA-SvPNu8qLh2ccPNvAU0abQk3AySkX
model_w_url = https://drive.google.com/uc?export=download&id=1gNvFNh8c-C7Vq6ol8mAG0e_i13eOVSeQ
